workspace(
    name="paceappui",
    managed_directories = {
        "@npm1": [
            "project1/node_modules"
        ],
        "@npm2": [
            "project2/node_modules"
        ]
    },
)

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

git_repository(
    name = "bazel_skylib",
    tag = "0.9.0",
    remote = "git@gitlab.eng.vmware.com:core-build/mirrors_github_bazel-skylib.git",
)

load("@bazel_skylib//:bzl_library.bzl", "bzl_library")

git_repository(
    name = "build_bazel_rules_nodejs",
    tag = "0.35.0",
    remote = "git@git.eng.vmware.com:core-build/mirrors_github_rules_nodejs.git",
)


load("@build_bazel_rules_nodejs//:defs.bzl", "node_repositories", "npm_install")

node_repositories(
    node_version = "10.10.0",
    node_repositories = {
        "10.10.0-darwin_amd64": ("node-v10.10.0-darwin-x64.tar.gz", "node-v10.10.0-darwin-x64", "00b7a8426e076e9bf9d12ba2d571312e833fe962c70afafd10ad3682fdeeaa5e"),
        "10.10.0-linux_amd64": ("node-v10.10.0-linux-x64.tar.xz", "node-v10.10.0-linux-x64", "686d2c7b7698097e67bcd68edc3d6b5d28d81f62436c7cf9e7779d134ec262a9"),
        "10.10.0-windows_amd64": ("node-v10.10.0-win-x64.zip", "node-v10.10.0-win-x64", "70c46e6451798be9d052b700ce5dadccb75cf917f6bf0d6ed54344c856830cfb"),
    },
    node_urls = [
        "https://build-artifactory.eng.vmware.com/nodejs-dist-cache/v{version}/{filename}"
    ]
)


npm_install(
    name = "npm1",
    always_hide_bazel_files = True,
    package_json = "//project1:package.json",
    package_lock_json = "//project1:package-lock.json",
)



npm_install(
    name = "npm2",
    always_hide_bazel_files = True,
    package_json = "//project2:package.json",
    package_lock_json = "//project2:package-lock.json",
)


